export const FETCH_EMPLOYEE_DETAILS_INITIATED = 'FETCH_EMPLOYEE_DETAILS_INITIATED';
export const FETCH_EMPLOYEE_DETAILS_SUCCESS = 'FETCH_EMPLOYEE_DETAILS_SUCCESS';
export const FETCH_EMPLOYEE_DETAILS_FAILED = 'FETCH_EMPLOYEE_DETAILS_FAILED';
